services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    networks:
      - app-network
    environment:
      - DEBUG=1
      - SERVICES=secretsmanager,dynamodb,kinesis
      - DYNAMODB_IN_MEMORY=1
      - EDGE_PORT=4566
    volumes:
      - localstack-data:/var/lib/localstack

networks:
  app-network:
    driver: bridge

volumes:
  localstack-data: