AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Handles all Cognito User Pool resources for the Event Streaming App.

Parameters:
  RootStackName:
    Type: String
    Description: The name of the root stack, used for naming resources.
  WebsiteDistributionDomainName:
    Type: String
    Description: The domain name of the CloudFront distribution for callback URLs.
  UserNames:
    Type: String
    Description: "Comma-separated list of usernames (email addresses) to create"
    Default: "test.user@example.com,edoatley@example.com,admin.user@example.com"
  AdminUserNames:
    Type: String
    Description: "Comma-separated list of usernames that should be added to the SecurityAdmins group"
    Default: "admin.user@example.com"


Resources:
  UserPreferencesUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${RootStackName}-UserPool"
      UsernameAttributes: [email]
      AutoVerifiedAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPreferencesUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${RootStackName}-AppClient"
      UserPoolId: !Ref UserPreferencesUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders: [COGNITO]
      CallbackURLs: [!Sub "https://${WebsiteDistributionDomainName}/index.html", "http://localhost:8000/index.html"]
      LogoutURLs: [!Sub "https://${WebsiteDistributionDomainName}/index.html", "http://localhost:8000/index.html"]
      AllowedOAuthFlows: [implicit, code]
      AllowedOAuthScopes: [openid, email, profile]

  TestScriptUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${RootStackName}-TestScriptClient"
      UserPoolId: !Ref UserPreferencesUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref UserPreferencesUserPool
      # The domain must be globally unique. We append the unique stack ID to ensure this.
      Domain: !Sub
        - 'uktv-guide-${Suffix}'
        - { Suffix: !Select [2, !Split ['/', !Ref 'AWS::StackId']] }

  SecurityAdminsGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: SecurityAdmins
      UserPoolId: !Ref UserPreferencesUserPool
      Description: "Group for application administrators with access to the admin screen."

  # Lambda execution role for user creation
  UserCreationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: UserCreationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${RootStackName}-UserCreation:*"
              - Effect: Allow
                Action:
                  - cognito-idp:AdminCreateUser
                  - cognito-idp:AdminGetUser
                  - cognito-idp:AdminSetUserPassword
                  - cognito-idp:AdminAddUserToGroup
                  - cognito-idp:AdminDeleteUser
                Resource: !GetAtt UserPreferencesUserPool.Arn
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                Resource: "*"

  # Lambda function to create users with random passwords
  # This function can be invoked directly via AWS CLI or SDK
  UserCreationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${RootStackName}-UserCreation"
      CodeUri: ../src/add_cognito_user/
      Handler: add_cognito_user.lambda_handler
      Runtime: python3.12
      Tracing: Active
      Role: !GetAtt UserCreationLambdaRole.Arn
      Timeout: 60

Outputs:
  UserPoolId:
    Description: "The ID of the Cognito User Pool"
    Value: !Ref UserPreferencesUserPool
  UserPoolArn:
    Description: "The ARN of the Cognito User Pool"
    Value: !GetAtt UserPreferencesUserPool.Arn
  UserPoolDomain:
    Description: "The full domain of the Cognito User Pool"
    Value: !Sub
      - 'uktv-guide-${Suffix}.auth.${Region}.amazoncognito.com'
      - Suffix: !Select [2, !Split ['/', !Ref 'AWS::StackId']]
        Region: !Ref AWS::Region
  UserCreationFunctionName:
    Description: "The name of the Lambda function for creating Cognito users"
    Value: !Ref UserCreationFunction
  UserNames:
    Description: "List of created usernames"
    Value: !Ref UserNames
  AdminUserNames:
    Description: "List of admin usernames"
    Value: !Ref AdminUserNames
  UserPoolClientId:
    Description: "The ID of the Cognito User Pool App Client for the web app"
    Value: !Ref UserPreferencesUserPoolClient
  TestScriptUserPoolClientId:
    Description: "The ID of the Cognito User Pool App Client for test scripts"
    Value: !Ref TestScriptUserPoolClient
  # Backward compatibility outputs
  TestUsername:
    Description: "The username of the first test user (backward compatibility)"
    Value: !Select [0, !Split [",", !Ref UserNames]]
  AdminUsername:
    Description: "The username of the first admin user (backward compatibility)"
    Value: !Select [0, !Split [",", !Ref AdminUserNames]]
