AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template creates an IAM OIDC provider for GitHub Actions and an IAM role
  that GitHub Actions can assume to deploy the tv-event-streaming application.

Parameters:
  RoleName:
    Type: String
    Default: edoatley-tv-event-streaming-gh-actions
  RepositoryOwner:
    Type: String
    Default: edoatley
  RepositoryName:
    Type: String
    Default: tv-event-streaming
  SamDeploymentBucketPattern:
    Type: String
    Description: "S3 bucket name pattern for SAM deployment artifacts (e.g., 'aws-sam-cli-deploy-*' or specific bucket name)"
    Default: "aws-sam-cli-deploy-*"

Resources:
  GitHubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOidcProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub "repo:${RepositoryOwner}/${RepositoryName}:*"
      Policies:
        - PolicyName: GitHubActionsDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  # For deploying CloudFormation stacks, including nested stacks via SAM
                  - cloudformation:*
                  # For creating roles for Lambdas and other services, and passing them.
                  # This is a broad permission set required by CloudFormation to manage IAM resources.
                  - iam:*
                  # For creating and managing Lambda functions and event source mappings
                  - lambda:*
                  # For creating and managing API Gateways
                  - apigateway:*
                  # For creating and managing DynamoDB tables and streams
                  - dynamodb:*
                  # For creating and managing CloudWatch Log Groups for Lambdas and APIs
                  - logs:*
                  # For creating and managing Secrets Manager secrets
                  - secretsmanager:*
                  # For creating and managing Kinesis streams
                  - kinesis:*
                  # For creating and managing CloudFront distributions and OAIs
                  - cloudfront:*
                  # For creating and managing Cognito User Pools and related resources
                  - cognito-idp:*
                  # For creating and managing EventBridge Scheduler schedules for Lambdas
                  - scheduler:*
                  # For managing EventBridge triggers
                  - events:*
                  # For creating and managing KMS keys for encryption (e.g., Kinesis stream encryption)
                  - kms:*
                Resource: "*"
              # Restricted S3 permissions for SAM deployment bucket only
              - Effect: Allow
                Action:
                  # Specific S3 actions needed for SAM to upload templates and Lambda code packages
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:CreateBucket
                Resource:
                  - !Sub "arn:aws:s3:::${SamDeploymentBucketPattern}"
                  - !Sub "arn:aws:s3:::${SamDeploymentBucketPattern}/*"

Outputs:
  GitHubActionsRoleArn:
    Description: "The ARN of the IAM role for GitHub Actions"
    Value: !GetAtt GitHubActionsRole.Arn