openapi: "3.0.1"
info:
  title: "UK TV Guide User Preferences API"
  version: "1.0"
paths:
  /preferences:
    get:
      summary: "Get the authenticated user's preferences"
      security:
        - CognitoAuthorizer: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWSRegion}:lambda:path/2015-03-31/functions/${UserPreferencesFunctionArn}/invocations"
      responses:
        "200":
          description: "A list of the user's preferences"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPreferences"
    put:
      summary: "Set or replace the authenticated user's preferences"
      security:
        - CognitoAuthorizer: []
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWSRegion}:lambda:path/2015-03-31/functions/${UserPreferencesFunctionArn}/invocations"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPreferences"
      responses:
        "204":
          description: "Preferences updated successfully"
  /sources:
    get:
      summary: "Get all available streaming sources"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWSRegion}:lambda:path/2015-03-31/functions/${UserPreferencesFunctionArn}/invocations"
      responses:
        "200":
          description: "A list of all available sources"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Source"
  /genres:
    get:
      summary: "Get all available genres"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWSRegion}:lambda:path/2015-03-31/functions/${UserPreferencesFunctionArn}/invocations"
      responses:
        "200":
          description: "A list of all available genres"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Genre"
components:
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools

  schemas:
    UserPreferences:
      type: object
      properties:
        sources:
          type: array
          items:
            type: string
            description: "The simple ID of the source (e.g., '203')"
        genres:
          type: array
          items:
            type: string
            description: "The simple ID of the genre (e.g., '4')"
    Source:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
        regions:
          type: array
          items:
            type: string
    Genre:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string